using Xunit;
using Xunit.Abstractions;
using System;
using System.Collections.Generic;
using System.Linq;
using TripsAndTriads.Core;
using TripsAndTriads.Rules;
using TripsAndTriads.Tests.Helpers;

namespace TripsAndTriads.Tests.Simulation
{
    /// <summary>
    /// Measures win rates for procedurally generated player crews against
    /// the fixed AI hand (Vesna + Verity + 3 generated Streets).
    ///
    /// This is the primary balance tuning dataset for new player experience.
    /// The key question: of crews generated by CrewGenerator, what fraction
    /// can actually win their first game?
    ///
    /// Breakdowns produced:
    ///   - Overall win rate across all generated crews
    ///   - Win rate by hero faction (which factions produce winning crews?)
    ///   - Win rate by hero ability type (None / Compound / Copy)
    ///   - Score margin distribution
    ///   - Capture rate averages
    ///
    /// Target balance range: 40–65% overall win rate for generated crews.
    /// Below 40% means the AI is too hard for new players.
    /// Above 65% means generated crews are trivially strong.
    /// </summary>
    public class ProceduralBalanceTests
    {
        private readonly ITestOutputHelper _output;

        // Games per generated crew — higher = more accurate, slower
        private const int GamesPerCrew  = 20;
        // Number of distinct crews to generate
        private const int CrewSamples   = 200;
        // Total games = GamesPerCrew × CrewSamples
        private const int Seed          = 42;

        public ProceduralBalanceTests(ITestOutputHelper output)
        {
            _output = output;
        }

        /// <summary>
        /// Builds the fixed AI hand without needing CardDatabase:
        /// Vesna (capped to VesnaStartingCap=7) + Verity + 3 generated Streets.
        /// </summary>
        private static List<CardData> BuildAIHand(Random rng)
        {
            var usedNames = new System.Collections.Generic.HashSet<string>();
            var hand      = new List<CardData>();

            // Vesna — mirrors GameBoard AI hand construction
            var vesna = CardFactory.Vesna().Data;
            hand.Add(vesna);

            // Verity — fixed TopTier support
            hand.Add(CardFactory.Verity().Data);

            // 3 generated Streets
            for (int i = 0; i < 3; i++)
                hand.Add(CrewGenerator.GeneratePro(rng, usedNames)); // GeneratePro gives variety

            return hand;
        }

        // ── Overall win rate ──────────────────────────────────────────────────

        [Fact]
        public void GeneratedCrews_OverallWinRate_SummaryAndAssertion()
        {
            var rng        = new Random(Seed);
            int totalWins  = 0;
            int totalGames = 0;
            var allMargins = new List<int>();
            double totalCaptures = 0;

            for (int crew = 0; crew < CrewSamples; crew++)
            {
                var generatedCrew = CrewGenerator.Generate(rng);
                var playerHand    = CrewGenerator.SelectBestFive(generatedCrew)
                                        .Select(c => c).ToList();

                for (int g = 0; g < GamesPerCrew; g++)
                {
                    TestLogger.Clear();
                    var aiHand = BuildAIHand(rng);

                    var result = GameSimulator.RunGame(
                        playerHand, aiHand,
                        GameSimulator.Strategy.Greedy,
                        GameSimulator.Strategy.Greedy,
                        new MatchConfig { }, // base rules, no protocols
                        rng);

                    if (result.Winner == 1) totalWins++;
                    totalGames++;
                    allMargins.Add(result.P1FinalScore - result.P2FinalScore);
                    totalCaptures += result.TotalCaptures;
                }
            }

            double winRate   = (double)totalWins / totalGames;
            double avgMargin = allMargins.Average();
            double avgCap    = totalCaptures / totalGames;

            _output.WriteLine($"=== Procedural Crew Balance ({CrewSamples} crews × {GamesPerCrew} games) ===");
            _output.WriteLine($"Total games    : {totalGames}");
            _output.WriteLine($"Player wins    : {totalWins} ({winRate:P1})");
            _output.WriteLine($"AI wins        : {totalGames - totalWins} ({1 - winRate:P1})");
            _output.WriteLine($"Avg score margin (P1-P2): {avgMargin:F2}");
            _output.WriteLine($"Avg captures per game   : {avgCap:F2}");
            _output.WriteLine("");

            var marginGroups = allMargins
                .GroupBy(m => m).OrderBy(g => g.Key)
                .Select(g => $"  {g.Key,+4}: {g.Count(),5} ({(double)g.Count()/totalGames:P1})");
            _output.WriteLine("Score margin distribution:");
            foreach (var line in marginGroups) _output.WriteLine(line);

            // Sanity assertion — if this fails the game is extremely unbalanced
            Assert.True(winRate > 0.10,
                $"Generated crews win rate {winRate:P1} is catastrophically low — " +
                $"new players will almost never win their first game.");
            Assert.True(winRate < 0.95,
                $"Generated crews win rate {winRate:P1} is trivially high — " +
                $"the AI poses no challenge.");
        }

        // ── Win rate by hero faction ──────────────────────────────────────────

        [Fact]
        public void GeneratedCrews_WinRateByHeroFaction()
        {
            var rng         = new Random(Seed);
            var factionWins = new Dictionary<Faction, int>();
            var factionGames = new Dictionary<Faction, int>();

            foreach (Faction f in Enum.GetValues(typeof(Faction)))
            {
                if (f == Faction.None) continue;
                factionWins[f]  = 0;
                factionGames[f] = 0;
            }

            int crewCount = 0;
            while (crewCount < CrewSamples * 2) // generate more to hit all factions
            {
                var generatedCrew = CrewGenerator.Generate(rng);
                var hero          = generatedCrew.Find(c => c.Tier == Tier.Hero)!;
                var playerHand    = CrewGenerator.SelectBestFive(generatedCrew).ToList();

                if (!factionWins.ContainsKey(hero.Faction)) { crewCount++; continue; }

                for (int g = 0; g < GamesPerCrew; g++)
                {
                    TestLogger.Clear();
                    var result = GameSimulator.RunGame(
                        playerHand, BuildAIHand(rng),
                        GameSimulator.Strategy.Greedy,
                        GameSimulator.Strategy.Greedy,
                        new MatchConfig(), rng);

                    if (result.Winner == 1) factionWins[hero.Faction]++;
                    factionGames[hero.Faction]++;
                }
                crewCount++;
            }

            _output.WriteLine("=== Win Rate by Hero Faction ===");
            _output.WriteLine($"{"Faction",-14} {"Games",6} {"Wins",6} {"Win Rate",10}");
            _output.WriteLine(new string('-', 40));

            foreach (var faction in factionWins.Keys.OrderBy(f => f.ToString()))
            {
                int games = factionGames[faction];
                if (games == 0) continue;
                double wr = (double)factionWins[faction] / games;
                _output.WriteLine($"{faction,-14} {games,6} {factionWins[faction],6} {wr,10:P1}");
            }

            // Data collection — assert only that we got games for multiple factions
            Assert.True(factionGames.Count(kv => kv.Value > 0) >= 3,
                "Expected to see at least 3 factions represented");
        }

        // ── Win rate by hero ability type ─────────────────────────────────────

        [Fact]
        public void GeneratedCrews_WinRateByHeroAbilityType()
        {
            var rng         = new Random(Seed);
            var abilityWins  = new Dictionary<AbilityType, int>
            {
                { AbilityType.None,     0 },
                { AbilityType.Compound, 0 },
                { AbilityType.Copy,     0 },
            };
            var abilityGames = new Dictionary<AbilityType, int>
            {
                { AbilityType.None,     0 },
                { AbilityType.Compound, 0 },
                { AbilityType.Copy,     0 },
            };

            for (int crew = 0; crew < CrewSamples * 2; crew++)
            {
                var generatedCrew = CrewGenerator.Generate(rng);
                var hero          = generatedCrew.Find(c => c.Tier == Tier.Hero)!;
                var playerHand    = CrewGenerator.SelectBestFive(generatedCrew).ToList();

                if (!abilityWins.ContainsKey(hero.AbilityType)) continue;

                for (int g = 0; g < GamesPerCrew; g++)
                {
                    TestLogger.Clear();
                    var result = GameSimulator.RunGame(
                        playerHand, BuildAIHand(rng),
                        GameSimulator.Strategy.Greedy,
                        GameSimulator.Strategy.Greedy,
                        new MatchConfig(), rng);

                    if (result.Winner == 1) abilityWins[hero.AbilityType]++;
                    abilityGames[hero.AbilityType]++;
                }
            }

            _output.WriteLine("=== Win Rate by Hero Ability Type ===");
            _output.WriteLine($"{"Ability",-12} {"Games",6} {"Wins",6} {"Win Rate",10}");
            _output.WriteLine(new string('-', 38));

            foreach (var ability in abilityWins.Keys)
            {
                int games = abilityGames[ability];
                if (games == 0) continue;
                double wr = (double)abilityWins[ability] / games;
                _output.WriteLine($"{ability,-12} {games,6} {abilityWins[ability],6} {wr,10:P1}");
            }

            // Data assertion
            Assert.True(abilityGames[AbilityType.None] > 0, "Expected None ability games");
        }

        // ── Tuning constants reference ────────────────────────────────────────

        [Fact]
        public void GeneratedCrews_TuningConstants_PrintCurrentValues()
        {
            // Prints the balance constants used by CrewGenerator so the
            // output is self-documenting when tuning.
            _output.WriteLine("=== Current CrewGenerator Balance Constants ===");
            _output.WriteLine("Street: total 10–14, edges 2–5");
            _output.WriteLine("Pro:    total 16–22, edges 2–9");
            _output.WriteLine("Hero:   exactly 1 A, soft edge ≤ 4");
            _output.WriteLine("AbilityWeights: None=75%, Compound=15%, Copy=10%");
            _output.WriteLine("AI Vesna: 10/10/10/10, decays -2/turn (no cap)");
            _output.WriteLine("");
            _output.WriteLine("Target win rate: 40–65% for new player experience.");
            _output.WriteLine("If below 40%: raise Street/Pro stat bands or lower VesnaStartingCap.");
            _output.WriteLine("If above 65%: lower Street/Pro stat bands or raise VesnaStartingCap.");

            Assert.True(true); // always passes — this is a reference printout
        }
    }
}